version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./carga.sql:/docker-entrypoint-initdb.d/carga.sql
    ports:
      - "3306:3306"

  node:
    image: node:14
    container_name: node_container
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4040:3000"
    depends_on:
      - mysql
    command: sh -c "npm install && node index.js"

volumes:
  mysql-data:
